version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "30301:30301"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "30302:30302"
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"