version: '3'

services:
  psg-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
  psg-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - psg-frontend
      - psg-backend