version: '3.7'

networks:
    web:
#        driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - web
#  backend:
#    build:
#      context: .
#      dockerfile: backend/Dockerfile
#    networks:
#      - web
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - web
    ports:
      - "80:80"