// Mocks generated by Mockito 5.4.5 from annotations
// in psygomoku/test/unit/blocs/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:psygomoku/infrastructure/transport/i_game_transport.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IGameTransport].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGameTransport extends _i1.Mock implements _i2.IGameTransport {
  MockIGameTransport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Map<String, dynamic>> get onMessage => (super.noSuchMethod(
        Invocation.getter(#onMessage),
        returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
      ) as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<void> get onDisconnect => (super.noSuchMethod(
        Invocation.getter(#onDisconnect),
        returnValue: _i3.Stream<void>.empty(),
      ) as _i3.Stream<void>);

  @override
  _i3.Stream<_i2.ConnectionState> get onStateChanged => (super.noSuchMethod(
        Invocation.getter(#onStateChanged),
        returnValue: _i3.Stream<_i2.ConnectionState>.empty(),
      ) as _i3.Stream<_i2.ConnectionState>);

  @override
  _i3.Future<void> connect(String? signalData) => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [signalData],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> send(Map<String, dynamic>? data) => (super.noSuchMethod(
        Invocation.method(
          #send,
          [data],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
