name: Build and Deploy

on:
  push:
    branches: [ "master" ]

env:
  NOTHING: 5001

jobs:
  setup-build-publish-deploy:
    name: Build & Deploy
    runs-on: self-hosted
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & Deploy
      run: |
        docker compose up -d --build
